name: Rust
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: sudo apt-get install -y libasound2-dev libudev-dev
    - name: Build
      run: cargo build
    - name: Run Tests
      run: cargo test
